var imageWidth,imgDataPath="image.json",imgPath="https://weichao-io-1257283924.cos.ap-beijing.myqcloud.com/qldownload/%E5%8D%9A%E5%AE%A2/",imgThumbPath="https://weichao-io-1257283924.cos.ap-beijing.myqcloud.com/qldownload/%E5%8D%9A%E5%AE%A2/%E7%BC%A9%E7%95%A5%E5%9B%BE/",windowWidth=window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth;imageWidth=windowWidth<768?145:250;const photo={page:1,init:function(){var a=this;$.getJSON(imgDataPath,function(t){a.render(a.page,t),a.eventListen(t)})},constructHtml(t){var{imageWidth:t,imageX:a,imageY:i,name:e,imgPath:n,imgThumbPath:m,imgNameWithPattern:o,imgThumbNameWithPattern:d}=t;return`<div class="card lozad" style="width:${t}px">
                  <div class="ImageInCard" style="height:${t*i/a}px">
                        <a data-fancybox="gallery" href="${n}${e}/${o}">
                            <img  class="lazyload" data-src="${m}${e}/${d}"
                            src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                            onload="lzld(this)"
                            lazyload="auto">
                        </a>
                  </div>
                </div>`},render:function(t,a=[]){if(!(this.data=a).length)return;var i,e,n,m,o,d="";let h="";var l="",[a={}]=(a.forEach((t,a)=>{a=0===a?"active":"";h+=`<li class="nav-item" role="presentation">
          <a class="nav-link ${a} photo-tab" id="home-tab" photo-uuid="${t.name}" data-toggle="tab" href="#${t.name}"  role="tab" aria-controls="${t.name}" aria-selected="true">${t.name}</a>
        </li>`}),a);const{children:g=[],name:s}=a;g.forEach((t,a)=>{i=t.split(" ")[1],e=t.split(" ")[2],n=i.split(".")[0],o=t.split(" ")[0],m=o.split(".")[0],o=o.split(".")[1];t={imageWidth:imageWidth,imageX:m,imageY:o,name:s,imgName:n,imgPath:imgPath,imgThumbPath:imgThumbPath,imgNameWithPattern:i,imgThumbNameWithPattern:e};d+=this.constructHtml(t)}),l+=` <div class="tab-pane fade show active"  role="tabpanel" aria-labelledby="home-tab">${d}</div>`;a=`<ul class="nav nav-tabs" id="myTab" role="tablist">${h}</ul>`,l=`<div class="tab-content" id="myTabContent">${l}</div>`;$("#imageTab").append(a),$(".ImageGrid").append(l),this.minigrid()},eventListen:function(m){let o=this;var d,h,l,g,s;$('a[data-toggle="tab"]').on("shown.bs.tab",function(t){$(".ImageGrid").empty();const a=$(t.target).attr("photo-uuid");const{children:i,name:e}=m.find(t=>t.name===a)||{};let n="";i.forEach((t,a)=>{d=t.split(" ")[1],h=t.split(" ")[2],l=d.split(".")[0],s=t.split(" ")[0],g=s.split(".")[0],s=s.split(".")[1];t={imageWidth:imageWidth,imageX:g,imageY:s,name:e,imgName:l,imgPath:imgPath,imgThumbPath:imgThumbPath,imgNameWithPattern:d,imgThumbNameWithPattern:h};n+=o.constructHtml(t)}),$(".ImageGrid").append(n),o.minigrid()})},minigrid:function(){var t=new Minigrid({container:".ImageGrid",item:".card",gutter:12});t.mount(),$(window).resize(function(){t.mount()})}};photo.init();